# Generated by Django 4.2.2 on 2023-06-30 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 30, 8, 44, 5, 790576)),
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_activate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 30, 8, 44, 5, 790602)),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_by',
            field=models.UUIDField(null=True),
        ),
    ]
