# Generated by Django 4.2.2 on 2023-06-30 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_user_created_at_user_created_by_user_is_activate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 30, 8, 46, 21, 818953, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 30, 8, 46, 21, 818983, tzinfo=datetime.timezone.utc)),
        ),
    ]
